### ISSUE TITLE
New Family Block Not Responsive on Mobile

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1151]
Tested on a Nexus 4 using Chrome and Mozilla Firefox

![](https://dl.pushbulletusercontent.com/3qkDNRJlI3CJs3nlw9YQCmKVIJKokNeR/Screenshot_2015-07-13-22-34-19.png)

**Comment by garrettjohnson** [comment]
Current progress using pure responsive table CSS.

**TODO:**
- [ ] Normalize Bottom Border of stacked/non-stacked form groups. (Radio Elements & Name Field)
- [ ] Define label for cancel button (Cancel/Delete/Remove?)
- [ ] Is “Person #XX” an appropriate row header?


**Adult View**
![screenshot 2017-03-24 10 33 19](https://cloud.githubusercontent.com/assets/374209/24306313/6e4fad1e-107d-11e7-99bb-a41c2a4f3453.png)

**Child w/ Grade**
![screenshot 2017-03-24 10 35 14](https://cloud.githubusercontent.com/assets/374209/24306396/a8ee09d4-107d-11e7-9637-30a27ff03a55.png)

**Multiple People**
![screenshot 2017-03-24 10 35 39](https://cloud.githubusercontent.com/assets/374209/24306401/af5a8d1a-107d-11e7-9345-95f87eee6ae3.png)

**Comment by edmistj** [comment]
Looks great! Definitely a hug improvement until we can do a full redesign.
